nohup: ignoring input
/data/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:530: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)
['!f_00280', '!f_00279', '!f_00347']
Succ load dataset conf.
2 / 3 remained.
1 / 3 remained.
0 / 3 remained.
Succ load LFE table for op square.
Time Usage for data preprocessing is : 1.05
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    pa.run()
  File "/data/!workspace/automl/common/utils.py", line 65, in wrapper
    raise e
  File "/data/!workspace/automl/common/utils.py", line 61, in wrapper
    a = f(ins, *args)
  File "/data/!workspace/automl/dataset_for_classifier.py", line 80, in run
    self.operator_pretraining(**kwargs)
  File "/data/!workspace/automl/dataset_for_classifier.py", line 115, in operator_pretraining
    self.training_operator_performance(oprtr)
  File "/data/!workspace/automl/dataset_for_classifier.py", line 142, in training_operator_performance
    score_origin = self.run_training_model(df_raw_data=__df_raw_data,dataset_name = __dataset_name, label = __label)
  File "/data/!workspace/automl/dataset_for_classifier.py", line 226, in run_training_model
    scores_clf_cv = cross_val_score(clf_svc_cv, data_x, data_y, cv = 5)
  File "/data/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 391, in cross_val_score
    error_score=error_score)
  File "/data/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 232, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/data/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 1003, in __call__
    if self.dispatch_one_batch(iterator):
  File "/data/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 834, in dispatch_one_batch
    self._dispatch(tasks)
  File "/data/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 753, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/data/anaconda3/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 201, in apply_async
    result = ImmediateResult(func)
  File "/data/anaconda3/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 582, in __init__
    self.results = batch()
  File "/data/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/data/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/data/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 516, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/data/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py", line 1451, in fit
    y = self._validate_y(y, sample_weight)
  File "/data/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/gradient_boosting.py", line 2065, in _validate_y
    % n_trim_classes)
ValueError: y contains 1 class after sample_weight trimmed classes with zero weights, while a minimum of 2 classes are required.
