nohup: ignoring input
['!f_00280', '!f_00279', '!f_00347']
Succ load dataset conf.
2 / 3 remained.
1 / 3 remained.
0 / 3 remained.
Succ load LFE table for op square.
Time Usage for data preprocessing is : 0.04
<class 'str'>
0.0
2223793    0.0
27946      0.0
1349100    1.0
857152     0.0
3014390    0.0
          ... 
2548208    0.0
4483652    1.0
4711147    1.0
3284160    0.0
577964     0.0
Name: 18, Length: 5000000, dtype: object
2223793          0.0
27946            0.0
1349100    non_label
857152           0.0
3014390          0.0
             ...    
2548208          0.0
4483652    non_label
4711147    non_label
3284160          0.0
577964           0.0
Name: 18, Length: 5000000, dtype: object
[0.7981532 0.7983652 0.797566  0.7987198 0.7988408]
Accuracy: 0.798329 (+/- 0.0009)
/data/!workspace/automl/dataset_for_classifier.py:148: PerformanceWarning: indexing past lexsort depth may impact performance.
  for __feature in df_lfe_table.loc[__dataset_name,__label].index.get_level_values(0).unique():
Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '0.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 36, in <module>
    pa.run()
  File "/data/!workspace/automl/common/utils.py", line 65, in wrapper
    raise e
  File "/data/!workspace/automl/common/utils.py", line 61, in wrapper
    a = f(ins, *args)
  File "/data/!workspace/automl/dataset_for_classifier.py", line 80, in run
    self.operator_pretraining(**kwargs)
  File "/data/!workspace/automl/dataset_for_classifier.py", line 115, in operator_pretraining
    self.training_operator_performance(oprtr)
  File "/data/!workspace/automl/dataset_for_classifier.py", line 148, in training_operator_performance
    for __feature in df_lfe_table.loc[__dataset_name,__label].index.get_level_values(0).unique():
  File "/data/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1418, in __getitem__
    return self._getitem_tuple(key)
  File "/data/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 805, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/data/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 961, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "/data/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1418, in __getitem__
    return self._getitem_tuple(key)
  File "/data/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 805, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/data/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 910, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "/data/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 993, in _getitem_nested_tuple
    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
  File "/data/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 1850, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/data/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py", line 160, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/data/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 3729, in xs
    return self[key]
  File "/data/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/data/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '0.0'
